databaseChangeLog:
  - changeSet:
      id: 23
      author: imran
      changes:
        - createTable:
            tableName: deployment_errors
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: strategy_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: strategy_leg_id
                  type: BIGINT
              - column:
                  name: status
                  type: VARCHAR(255)
              - column:
                  name: description
                  type: text[]
              - column:
                  name: deployed_on
                  type: DATETIME
              - column:
                  name: error_code
                  type: VARCHAR(255)
              - column:
                  name: created_by
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: DATETIME
                  constraints:
                    nullable: false
              - column:
                  name: updated_by
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: DATETIME
                  constraints:
                    nullable: false
              - column:
                  name: delete_indicator
                  type: VARCHAR(255)

        - createSequence:
            incrementBy: 1
            sequenceName: deployment_errors_seq
            startValue: 1000
